### ISSUE TITLE
Farmer(1965)

### ISSUE THREAD

**Issue by trammell** [snowballstem/snowball-website#32]
Is there a more complete reference for Farmer(1965)?

https://github.com/snowballstem/snowball-website/blob/911c95309cd53bf3df3aaf0aa09943c21409e37e/texts/introduction.tt#L108

**Comment by ojwb** [comment]
Martin Porter wrote that text - I don't think he's on github, but see https://tartarus.org/martin/ or email the snowball mailing list which I know he still follows.

**Comment by ojwb** [comment]
I noticed there **is** a 1965 reference but it's for "Palmer FR (1965) A linguistic study of the English verb. Longmans, London." which is available on archive.org (you have to sign up for a free account and then you can "borrow" it for an hour at a time for free).  The referenced text is indeed on pp 2 and 3 of that - here's a screenshot of the relevant paragraph:

![Screenshot at 2023-08-21 09-49-42](https://github.com/snowballstem/snowball-website/assets/164061/6a75246b-ca88-4f74-982c-db1c9059dfd5)
![Screenshot at 2023-08-21 09-49-10](https://github.com/snowballstem/snowball-website/assets/164061/540a670a-bef7-4dfa-b864-a501c94195e9)

I'll correct "Farmer" to say "Palmer" - thanks for raising this.
