### ISSUE TITLE
Files from http://snowballstem.org/download.html are not available

### ISSUE THREAD

**Issue by za-arthur** [snowballstem/snowball-website#8]
Files that can be downloaded from http://snowballstem.org/download.html page are not available. Direct links not available:
- http://snowballstem.org/dist/libstemmer_c.tgz
- http://snowballstem.org/dist/libstemmer_java.tgz
- http://snowballstem.org/dist/snowball_code.tgz
- http://snowballstem.org/dist/snowball_web_and_code.tgz
- http://snowballstem.org/dist/snowball_all.tgz

Artur

**Comment by ojwb** [comment]
Yeah, we've not made a release since the new website was created - I've just commented out those links for now, and provided a link to the downloads on the old website instead.
